apiVersion: batch/v1
kind: Job
metadata:
  name: autoby-job
spec:
  template:
    spec:
      containers:
      - name: autoby-job
        image: yash5090/autoby:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
