apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoby-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: autoby
  template:
    metadata:
      labels:
        app: autoby
    spec:
      containers:
        - name: autoby
          image: yash5090/autoby:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
